### PR TITLE
API GW base files

### PR DESCRIPTION
**Pull request by byzek**
Needs testing and more scripts to auto-install (and maybe install differently depending on k8s distro) but it works on microk8s as-is

### CODE REVIEW

**Comment by ubaumann** [comment]
Hi @byzek 

I saw your PR and was wondering if you might be interested in adding our Jalapeno GW to the main jalapeno repository.
- https://jalapeno-api-gateway.github.io/jagw-docs/
- https://github.com/jalapeno-api-gateway/jagw

If any features are missing, we can add them to our GW.

**Comment by byzek** [comment]
> 

Hi @ubaumann, I had no idea this existed! Let me scan through to make sense of it and get back to you....but that will almost certainly be a better approach than what I've done.

**Comment by byzek** [comment]
Hey @ubaumann, sorry for the delay in getting back. I've had a chance to look through your docs and I think it makes a lot of sense to incorporate your API GW. I have some slightly different ideas about the role that the API GW should be serving but I think they would be easily incorporated.

I'll go ahead and close this PR and we'll start figuring out how to incorporate your repo.

**Comment by byzek** [comment]
Sounds good. I’m a little busy this week but will revisit next week.

From: ubaumann ***@***.***>
Date: Tuesday, December 6, 2022 at 10:27 AM
To: cisco-open/jalapeno ***@***.***>
Cc: Jeff Byzek (byzek) ***@***.***>, Mention ***@***.***>
Subject: Re: [cisco-open/jalapeno] API GW base files (PR #65)

Hi @byzek<https://github.com/byzek>

We can discuss it in an issue in our repository or set up a call to discuss your features and how we can work together on this.
urs.baumann[at]ost.ch

**Comment by ubaumann** [comment]
We don't have notably better days in the first weeks of the year. This will probably change in February.
As we are based in Switzerland, American morning hours fit best with our late afternoon.

**Pull request closed without merging**
