### PR TITLE
Create example-queries.md

### PR DESCRIPTION
**Pull request by brmcdoug**

### CODE REVIEW

**Comment by brmcdoug** [comment]
got a request to post some sample ArangoDB queries

**Review by byzek — CHANGES_REQUESTED** [review]
Could you provide a picture to reference also so the data in the requests make more sense?

**Comment by brmcdoug** [comment]
> Could you provide a picture to reference also so the data in the requests make more sense?

diagram with notation added

**Review by byzek — APPROVED** [review]
much better!

**Pull request merged**
